#!/usr/bin/env python

import os, sys, stat

exclude = [".DS_Store"]
include = ['wav', 'flac', 'aiff', 'shn', 'jpg', 'JPG']
def cmp(a, b):
    A = os.stat(a)[stat.ST_MTIME]
    B = os.stat(b)[stat.ST_MTIME]
    if A > B:
        return 1
    elif B>A:
        return -1
    return 0
    

def doit(input, base, ext, start=1):
    os.chdir(input)
    l = os.listdir(".")
    #l.sort(cmp)
    l.sort()
    num = start
    was = None
    for i in l:
        if sum([i.endswith(x) for x in include ]) == 1:
            out = '%s%02d.%s' % (base,num,ext)
            print i, ">>>", out
            if was and was == i:
                i = "__"+was
                was = None
            if os.path.isfile(out):
                os.rename(out, "__"+out)
                was = out
            os.rename(i, out)
            num += 1
    
if __name__ == "__main__":
    if len(sys.argv) == 4:
        doit(sys.argv[1], sys.argv[2], sys.argv[3])
    elif len(sys.argv) == 5:
        doit(sys.argv[1], sys.argv[2], sys.argv[3], int(sys.argv[4])) 
