#!/usr/bin/env python

import os, sys, stat

from optparse import OptionParser


exclude = [".DS_Store"]
include = ['wav', 'flac', 'aiff', 'shn', 'jpg', 'JPG']
def cmp(a, b):
    A = os.stat(a)[stat.ST_MTIME]
    B = os.stat(b)[stat.ST_MTIME]
    if A > B:
        return 1
    elif B>A:
        return -1
    return 0
    

def doit(input, base, ext, start=1, alpha=False):
    os.chdir(input)
    l = os.listdir(".")
    if alpha:
        l.sort()
    else:
        l.sort(cmp)
    num = start
    was = None
    for i in l:
        if sum([i.endswith(x) for x in include ]) == 1:
            out = '%s%02d.%s' % (base,num,ext)
            print i, ">>>", out
            if was and was == i:
                i = "__"+was
                was = None
            if os.path.isfile(out):
                os.rename(out, "__"+out)
                was = out
            os.rename(i, out)
            num += 1
    
if __name__ == "__main__":
    usage = """rsplits |-a| <input_dir> <basename> <extension> |<startnum>|""
       renames files with extensions wav/flac/aiff/shn/jpg/JPG
       example:  rsplits . mmw2012-09-20s1t flac
       startnum: start on nth file
       -a alpha: use alpha order instead of default modified order
    """
    parser = OptionParser(usage)
    parser.add_option("-a", dest='a', default=False, action="store_true")

    options, args = parser.parse_args()


    if len(args) == 3:
        doit(*args, alpha=options.a)
    elif len(args) == 4:
        doit(args[0], args[1], args[2], int(args[3]), alpha=options.a)
